<?php
//$products = $this->PromoListable();

//echo '<pre>'; print_r($products); //eğer bunu açarsan tüm kullancagın elemanları gorursun


?>
<?php //foreach ($products as $product): ?>
    <div class="itemslider-wrapper slider-arrows1 slider-arrows1-pos-top-right slider-pagination1">
        <div id="itemslider-featured" class="itemslider itemslider-responsive products-grid size-xs centered owl-carousel owl-theme"
             style="opacity: 1; display: block;">
            <div class="owl-wrapper-outer">
                <div class="owl-wrapper" style="width: 21960px; left: 0px; display: block; transition: all 200ms ease; transform: translate3d(-3294px, 0px, 0px);">
                    <div class="owl-item" style="width: 183px;">
                        <div class="item">

                            <div class="product-image-wrapper" style="max-width:196px;">

                                <a href="https://www.sevil.com.tr/giorgio-armani-ecstasy-shine-ruj.html" title="Giorgio Armani Ecstasy Shine Ruj" class="product-image">

                                    <img class="lazyOwl"
                                         src="https://sevil-8dc0.kxcdn.com/media/catalog/product/cache/1/small_image/196x196/9df78eab33525d08d6e5fb8d27136e95/l/o/lo-l9810000.jpg"
                                         alt="Giorgio Armani Ecstasy Shine Ruj" style="display: inline;">


                                    <span class="sticker-wrapper top-left"><span class="sticker new">Yeni</span></span> </a>

                            </div> <!-- end: product-image-wrapper -->

                            <strong class="product-name"><a href="https://www.sevil.com.tr/giorgio-armani-ecstasy-shine-ruj.html" title="Giorgio Armani Ecstasy Shine Ruj">Giorgio
                                    Armani Ecstasy Shine Ruj</a></strong>
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:100%"></div>
                                </div>
                                <span class="amount">1 Yorum</span>
                            </div>
                            <div class="price" id="amlabel-product-price-24743" style="display:none"></div>


                            <div class="price-box">
                                                                <span class="regular-price" id="product-price-24737bac19e2d297cca4ae58716b6d5888996">
                                            <span class="price">165,00&nbsp;TL</span>                                    </span>

                            </div>

                            <div class="actions">


                            </div>

                        </div>
                    </div>
                </div>
            </div>


        </div> <!-- end: itemslider -->
    </div>
<?php //endforeach; ?>